# ?はnullでもいいことを表している。

users:
  documentID: auto
    name: String
    email: String
    avatorURL: String?
    groupId: Arr

groups:
  documentID: auto
    name: String
    description: String
    userIds: Arr
      messages: subCollection
        documentID: auto
          message: String
          imgae: String?
          user: 
            id: String
            name: String
          
